Repository copier-org/copier, pull requests merged in 2020-05, with the labels that each got.

#202 Recommend copier-template GH topic
  README.md
Labels: Type:Enhancement

#188 [IMP] Make prompts more beautiful
  copier/config/user_data.py
Labels: Type:Enhancement

#205 Add minimum copier version verification
  README.md
  copier/config/factory.py
  poetry.lock
  pyproject.toml
  tests/demo_minimum_version/README.md
  tests/demo_minimum_version/copier.yml
  tests/test_minimum_version.py
Labels: Type:Enhancement

#207 Improve tasks & migration docs, prepare v3.1.0 release
  CHANGELOG.md
  README.md
Labels: Type:Enhancement

#211 Stop using deprecated semver.compare function
  copier/config/factory.py
Labels: Type:Maintenance

#212 Add automerge
  .github/workflows/automerge.yml
Labels: automerge

#193 Add subdirectory option
  README.md
  copier/cli.py
  copier/config/factory.py
  copier/config/objects.py
  copier/main.py
  tests/demo_subdirectory/api_project/api_readme.md
  tests/demo_subdirectory/conf_project/conf_readme.md
  tests/demo_subdirectory/copier.yml
  tests/test_config.py
  tests/test_copy.py
  tests/test_subdirectory.py
Labels: Type:Enhancement
