Repository copier-org/copier, pull requests merged in 2020-02, with the labels that each got.

#121 Add migrations support
  README.md
  copier/cli.py
  copier/config/factory.py
  copier/config/objects.py
  copier/main.py
  copier/tools.py
  copier/vcs.py
  pyproject.toml
  setup.cfg
  tests/demo_updatediff_repo.bundle
  tests/test_config.py
  tests/test_copy.py
  tests/test_updatediff.py
Labels: Type:Enhancement

#123 Fix copier --help
  copier/cli.py
  tests/test_cli.py
Labels: Type:Bug

#124 Exclude recursively
  README.md
  copier/config/objects.py
  copier/main.py
  tests/demo_exclude/bad/subdir/file.txt
  tests/demo_exclude/copier.yml
  tests/test_exclude.py
Labels: Type:Bug

#122 Install into .venv by default
  Makefile
Labels: Type:Bug

#134 Remove .vscode
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
Labels: Type:Maintenance

#135 Supply the copier binary and install it in CI
  .github/workflows/ci.yml
  copier/main.py
  pyproject.toml
  tests/test_updatediff.py
Labels: Type:Bug

#137 Implement build + publish via CI
  .github/workflows/ci.yml
  pyproject.toml
Labels: Type:Maintenance

#142 Add Credits section to readme
  README.md
Labels: Type:Enhancement

#136 Include other config files
  README.md
  copier/config/user_data.py
  copier/tools.py
  poetry.lock
  pyproject.toml
  tests/demo_config_transclude/demo/copier.yml
  tests/demo_config_transclude/include_me.yml
  tests/test_config.py
Labels: Type:Enhancement

#144 Safer & faster YAML dump
  copier/tools.py
Labels: Type:Enhancement

#145 Make sure --data works
  copier/config/user_data.py
  pyproject.toml
  tests/test_complex_questions.py
Labels: Type:Bug
