Repository copier-org/copier, pull requests merged in 2020-09, with the labels that each got.

#266 Update docs dependencies versions
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: Type:Enhancement, Type:Maintenance

#271 Reorder reference docs
  copier/main.py
  docs/api/index.md
  docs/reference/cli.md
  docs/reference/config/factory.md
  docs/reference/config/objects.md
  docs/reference/config/user_data.md
  docs/reference/main.md
  docs/reference/tools.md
  docs/reference/types.md
  docs/reference/vcs.md
Labels: Type:Enhancement

#272 Fix broken docs links
  mkdocs.yml
Labels: Type:Enhancement, Type:Maintenance

#274 Make exclude extend if called from CLI/API
  copier/config/factory.py
  docs/configuring.md
  tests/test_config.py
  tests/test_copy.py
Labels: automerge

#275 Remove --only-diff flag
  copier/cli.py
  copier/config/factory.py
  docs/configuring.md
  tests/test_updatediff.py
Labels: automerge

#276 Allow running copier when installed in editable mode
  copier/config/factory.py
  tests/test_minimum_version.py
Labels: Type:Enhancement, automerge

#282 Configure gitpod
  .gitpod.yml
  README.md
Labels: Type:Enhancement, Type:Maintenance

#283 Fix gitpod configuration
  .gitpod.dockerfile
  .gitpod.yml
  .theia/settings.json
  CONTRIBUTING.md
Labels: Type:Enhancement, Type:Maintenance
