Repository copier-org/copier, pull requests merged in 2021-11, with the labels that each got.

#434 fix!: always compare versions as PEP440 strings
  CHANGELOG.md
  copier/main.py
  copier/template.py
  docs/configuring.md
  poetry.lock
  pyproject.toml
Labels: bug, enhancement

#471 test(migrations): add test for new PEP 440 environment variables in migrations
  tests/demo_migrations/migrations.py
  tests/test_migrations.py
Labels: maintenance

#472 perf(clone): clone faster without blobs
  CHANGELOG.md
  README.md
  copier/vcs.py
Labels: enhancement

#475 relax git semver parsing
  copier/vcs.py
Labels: bug

#476 raise CopierAnswersInterrupt on partial answers
  CHANGELOG.md
  copier/errors.py
  copier/main.py
  tests/helpers.py
  tests/test_interrupts.py
  tests/test_prompt.py
Labels: enhancement
