Repository copier-org/copier, pull requests merged in 2022-08, with the labels that each got.

#719 feat: add validator field to Question
  copier/user_data.py
  docs/configuring.md
  tests/conftest.py
  tests/test_complex_questions.py
Labels: enhancement

#739 Alternative install with Conda
  README.md
Labels: documentation

#759 build(isort): install with poetry
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: bug, dependencies
